---
- name: restart alertmanager
  systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted
  become: true
  tags: alertmanager

- name: reload alertmanager
  systemd:
    name: alertmanager
    state: reloaded
  become: true
  tags: alertmanager

- name: reload consul
  systemd:
    name: consul
    state: reloaded
  become: true
  tags: alertmanager
