---
- name: restart alertmanager
  systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted
  become: true
  tags: alertmanager

- name: reload alertmanager
  systemd:
    name: alertmanager
    state: reloaded
  become: true
  tags: alertmanager

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: alertmanager
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: alertmanager
  become: true